<a href="https://colab.research.google.com/github/mossytreesandferns/DataScience2/blob/master/Algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Mount my drive- run the code, go to the link, accept.
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
#Change working directory to make it easier to access the files
import os
os.chdir("/content/gdrive/My Drive/Colab Notebooks/")
os.getcwd()

'/content/gdrive/My Drive/Colab Notebooks'

In [3]:
import numpy as np
import random

## Binary Search
Sorted arrays. Search takes the number of steps max to divide array in half until item is found.  This amounts to O(logn) runtime.

In [11]:
np.random.seed(42)
nums = np.random.randint(1,150,100)
nums

array([103,  93,  15, 107,  72,  21, 103, 122,  75,  88, 117, 100, 104,
       131,  53,   2,  88,  38, 130,  21,  58,  22,  89,  49,  59,  15,
        51, 108,  55,  64, 131,  51, 135,  21,  73,  18, 132,  89,  60,
        14,   9,  90,  53, 130,  84,  92, 111,   8,  35,  81,  50, 104,
       132,   2, 134,  54, 106,   4,  54, 146,  44,  14,  95,  48,  15,
        40,  82, 111,  53,  24, 124,  41,  15,  45,  65,  89,  71,   9,
        88, 129, 136,  63, 139,  81, 136,  33, 123,   5,  41,  28, 135,
        72,  12,  33,  48,  62,  37,  99, 104,  35])

In [12]:
nums = sorted(nums)
nums[:15]

[2, 2, 4, 5, 8, 9, 9, 12, 14, 14, 15, 15, 15, 15, 18]

In [13]:
serch_term = 104

In [14]:
# Linear
def linear_search(array, search_term):
  for i in array:
    if array[i] == search_term:
      return True
    else:
      return False  

In [23]:
# Iterative

def binary_search_it(array, search_term):
  low = 0
  high = len(array) -1
  while low < high:
    mid = (low + high)//2
    if search_term == array[mid]:
      return True
    elif search_term < array[mid]: 
      high = mid - 1
    elif search_term > array[mid]:
      low = mid + 1
  return False    

binary_search_it(nums, 111), binary_search_it(nums, 3), binary_search_it(nums, 149)  

(True, False, False)

In [34]:
# Recursive
def binary_search_re(array, search_term, low, high):
    if low > high:
      return False
    else:  
      mid = len(array)//2
      if search_term == array[mid]:
          return True

      elif search_term > array[mid]:
          return binary_search_re(array[mid +1:], search_term, low, mid-1)

      elif search_term < array[mid]:
          return binary_search_re(array[:mid-1], search_term, mid + 1, high) 

binary_search_re(nums, 111, nums[0], nums[-1]), binary_search_re(nums, 3,nums[0], nums[-1]), binary_search_re(nums, 14, nums[0], nums[-1])       

(True, False, False)

## Bubble sort
Nested loops are necessary because iteration will only move through the array with the item at index 0 if only one loop is implemented.<br>
Runtime O(n^2) Space O(1) (sorting performed in place). No external data structures required.

In [35]:
np.random.seed(29)
nums = np.random.randint(1,150,100)
nums

array([116,  35,  41,  97, 106, 114,  98,  95,  95,  70, 149,  65, 131,
        16, 103,  59,  12,  25,   4, 124,  79,  27,  14,  24,  33,  51,
        67, 105,   2, 124,  21, 119,  60, 135,  85,  45,  30, 108, 122,
        60,  48, 133, 116,   5,  79,  17,   5,  68,  47,  79, 133,  12,
        34,  79, 149,  87,  15,  10,  55,  93,  33, 101,  56,   7,  34,
        86,  19,  93,  19, 132, 121,  72,  20,  96,  18,  66, 124,  93,
        95,  98,   1,  92,  53,  66,  60,  78, 134,  14,  70,  74, 141,
       147, 108,  20,  50,   7,  89, 126,  88, 146])

In [38]:
def bubble_sort(array):
  for j in range(len(array)):
    for i in range(len(array)-1):
      if array[i] > array[i + 1]:
        placeholder = array[i]
        array[i] = array[i+1]
        array[i+1] = placeholder
  return array      

bubble_sort(nums)

array([  1,   2,   4,   5,   5,   7,   7,  10,  12,  12,  14,  14,  15,
        16,  17,  18,  19,  19,  20,  20,  21,  24,  25,  27,  30,  33,
        33,  34,  34,  35,  41,  45,  47,  48,  50,  51,  53,  55,  56,
        59,  60,  60,  60,  65,  66,  66,  67,  68,  70,  70,  72,  74,
        78,  79,  79,  79,  79,  85,  86,  87,  88,  89,  92,  93,  93,
        93,  95,  95,  95,  96,  97,  98,  98, 101, 103, 105, 106, 108,
       108, 114, 116, 116, 119, 121, 122, 124, 124, 124, 126, 131, 132,
       133, 133, 134, 135, 141, 146, 147, 149, 149])

## Selection sort
Item by item, array is continually divided into two sections: the sorted section and the unsorted section. Switching of the smallest value.<br>
Runtime O(n^2) average and worst. Space O(1) (sorting performed in place).

In [43]:
def selection_sort(array):
  for i in range(0,len(array)-1):
    minimum_index = array[i]
    for j in range(i + 1, len(array)):
      if array[j] < minimum_index:
        minimum_index = array[j]
  return array


selection_sort(nums)  

array([  1,   2,   4,   5,   5,   7,   7,  10,  12,  12,  14,  14,  15,
        16,  17,  18,  19,  19,  20,  20,  21,  24,  25,  27,  30,  33,
        33,  34,  34,  35,  41,  45,  47,  48,  50,  51,  53,  55,  56,
        59,  60,  60,  60,  65,  66,  66,  67,  68,  70,  70,  72,  74,
        78,  79,  79,  79,  79,  85,  86,  87,  88,  89,  92,  93,  93,
        93,  95,  95,  95,  96,  97,  98,  98, 101, 103, 105, 106, 108,
       108, 114, 116, 116, 119, 121, 122, 124, 124, 124, 126, 131, 132,
       133, 133, 134, 135, 141, 146, 147, 149, 149])

## Insertion sort
Creating a sorted list from left to right.  <br>
Runtime O(n^2). Space O(n).

In [44]:
def insertion_sort(array):
    for i in range(1, len(array)):
        for j in range(i-1, 0, -1):
            if array[j] > array[j+1]:
                array[j], array[j+1] = array[j+1], array[j]
    return array

insertion_sort(nums)    

array([  1,   2,   4,   5,   5,   7,   7,  10,  12,  12,  14,  14,  15,
        16,  17,  18,  19,  19,  20,  20,  21,  24,  25,  27,  30,  33,
        33,  34,  34,  35,  41,  45,  47,  48,  50,  51,  53,  55,  56,
        59,  60,  60,  60,  65,  66,  66,  67,  68,  70,  70,  72,  74,
        78,  79,  79,  79,  79,  85,  86,  87,  88,  89,  92,  93,  93,
        93,  95,  95,  95,  96,  97,  98,  98, 101, 103, 105, 106, 108,
       108, 114, 116, 116, 119, 121, 122, 124, 124, 124, 126, 131, 132,
       133, 133, 134, 135, 141, 146, 147, 149, 149])

## Quick sort
Recursive.  Choose a pivot, usually the first or last element in array, and sort elements that are smaller to the left and elements that are larger to the right.  Swapping the first true after the first false with the first false. Then the array can be divided in half for each half to be sorted, etc... <br>
Runtime avg, worst: O(nlogn), O(n^2). Space O(logn) if no empty arrays are used, O(n) if they are.

In [46]:
def quicksort(array):
    if len(array) <= 1:
        return array
    left, mid_pivot, right = [],[],[]
    pivot = array[random.randint(0,len(array)-1)]

    for i in array:
        if i < pivot:
            left.append(i)
        elif i == pivot:
            mid_pivot.append(i)
        else:
            right.append(i) 
    return quicksort(left) + mid_pivot + quicksort(right)

quicksort(nums)      

[1,
 2,
 4,
 5,
 5,
 7,
 7,
 10,
 12,
 12,
 14,
 14,
 15,
 16,
 17,
 18,
 19,
 19,
 20,
 20,
 21,
 24,
 25,
 27,
 30,
 33,
 33,
 34,
 34,
 35,
 41,
 45,
 47,
 48,
 50,
 51,
 53,
 55,
 56,
 59,
 60,
 60,
 60,
 65,
 66,
 66,
 67,
 68,
 70,
 70,
 72,
 74,
 78,
 79,
 79,
 79,
 79,
 85,
 86,
 87,
 88,
 89,
 92,
 93,
 93,
 93,
 95,
 95,
 95,
 96,
 97,
 98,
 98,
 101,
 103,
 105,
 106,
 108,
 108,
 114,
 116,
 116,
 119,
 121,
 122,
 124,
 124,
 124,
 126,
 131,
 132,
 133,
 133,
 134,
 135,
 141,
 146,
 147,
 149,
 149]

## Merge sort
Array divided into two repeatedly until there are many arrays of 1 item.  Items are merged together into lists that are in the correct order.<br>
Time O(n*Log n) in both cases.  Space O(n).

In [49]:
def merge(array1,array2): # Helper function
    array3 = []
    array1_index, array2_index = 0,0
    while array1_index < len(array1) and array2_index < len(array2):
        if array1[array1_index] < array2[array2_index]:
            array3.append(array1[array1_index])
            array1_index += 1
        else:
            array3.append(array2[array2_index])
            array2_index += 1   
    if array1_index == len(array1): 
        array3.extend(array2[array2_index:]) 
    else:
        array3.extend(array1[array1_index:])            
    return array3


def merge_sort(array):
    if len(array) <= 1:
        return array
    left, right = merge_sort(array[:len(array)//2]), merge_sort(array[len(array)//2:])  
    return merge(left, right) 


merge_sort(nums)     

[1,
 2,
 4,
 5,
 5,
 7,
 7,
 10,
 12,
 12,
 14,
 14,
 15,
 16,
 17,
 18,
 19,
 19,
 20,
 20,
 21,
 24,
 25,
 27,
 30,
 33,
 33,
 34,
 34,
 35,
 41,
 45,
 47,
 48,
 50,
 51,
 53,
 55,
 56,
 59,
 60,
 60,
 60,
 65,
 66,
 66,
 67,
 68,
 70,
 70,
 72,
 74,
 78,
 79,
 79,
 79,
 79,
 85,
 86,
 87,
 88,
 89,
 92,
 93,
 93,
 93,
 95,
 95,
 95,
 96,
 97,
 98,
 98,
 101,
 103,
 105,
 106,
 108,
 108,
 114,
 116,
 116,
 119,
 121,
 122,
 124,
 124,
 124,
 126,
 131,
 132,
 133,
 133,
 134,
 135,
 141,
 146,
 147,
 149,
 149]