<a href="https://colab.research.google.com/github/mossytreesandferns/DataScience2/blob/master/UsefulCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Mount my drive- run the code, go to the link, accept.
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
#Change working directory to make it easier to access the files
import os
os.chdir("/content/gdrive/My Drive/Colab Notebooks/")
os.getcwd()

'/content/gdrive/My Drive/Colab Notebooks'

## The random() module

In [1]:
import numpy as np
np.random.seed(41)
print(np.random.rand())
print(np.random.randint(1,150))
print(np.random.sample(5))
array = [1,2,3,4,5]
print(np.random.choice(array, 7))
print(np.random.shuffle(array))
print(array)
print(np.random.permutation(array))
np.random.normal(array)

0.25092362374494015
141
[0.32097339 0.15535934 0.60056724 0.92435824 0.78786441]
[1 4 4 3 1 5 2]
None
[3, 2, 5, 1, 4]
[1 2 5 3 4]


array([1.96714075, 3.14242738, 4.39022199, 2.46941639, 5.49267884])

## map(), enumerate(), zip()

In [7]:
a = map(lambda x: x**2, array)
list(a)

[9, 4, 25, 1, 16]

In [9]:
b = map(float,array)
list(b)

[3.0, 2.0, 5.0, 1.0, 4.0]

In [11]:
a = ['a','b','c','d','e']
b = enumerate(a)
list(b)

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd'), (4, 'e')]

In [12]:
a = ['a','b','c','d','e']
b = enumerate(a)
[*b]

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd'), (4, 'e')]

In [21]:
names = ['Jerry', 'Terry', 'Gary', 'Mary', 'Larry', 'Barry']
# old fashioned for loop
indexed_names = []
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

# list comprehension
indexed_names_comp = [(i,name) for i,name in enumerate(names)]
print(indexed_names_comp)

# unpacking with list comprehenstion
indexed_names_unpack = [*enumerate(names, start=1)]  # * makes it so that a list is printed without append, or list comprehension, [] == list()
print(indexed_names_unpack)

[(0, 'Jerry'), (1, 'Terry'), (2, 'Gary'), (3, 'Mary'), (4, 'Larry'), (5, 'Barry')]
[(0, 'Jerry'), (1, 'Terry'), (2, 'Gary'), (3, 'Mary'), (4, 'Larry'), (5, 'Barry')]
[(1, 'Jerry'), (2, 'Terry'), (3, 'Gary'), (4, 'Mary'), (5, 'Larry'), (6, 'Barry')]


## list comprehension with zip() and enumerate()

In [22]:
l = [1.1,2.2,3.3,4.4,5.5]

squared = [x**2 for x in l]
squared

[1.2100000000000002,
 4.840000000000001,
 10.889999999999999,
 19.360000000000003,
 30.25]

In [23]:
d = [x -3 for x in l if x > 3]
d

[0.2999999999999998, 1.4000000000000004, 2.5]

In [24]:
[*range(18)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

In [28]:
[*enumerate(names)]

[(0, 'Jerry'),
 (1, 'Terry'),
 (2, 'Gary'),
 (3, 'Mary'),
 (4, 'Larry'),
 (5, 'Barry')]

In [25]:
randtime = [*range(0,60, 10)]

# Enumerating with a list of strings
show_time = [(names[name], time) for name, time in enumerate(randtime)]
show_time

[('Jerry', 0),
 ('Terry', 10),
 ('Gary', 20),
 ('Mary', 30),
 ('Larry', 40),
 ('Barry', 50)]

In [26]:
ziptime = zip(randtime, names)
[*ziptime]

[(0, 'Jerry'),
 (10, 'Terry'),
 (20, 'Gary'),
 (30, 'Mary'),
 (40, 'Larry'),
 (50, 'Barry')]

In [29]:
zip2time = zip(names, randtime)
[*zip2time]

[('Jerry', 0),
 ('Terry', 10),
 ('Gary', 20),
 ('Mary', 30),
 ('Larry', 40),
 ('Barry', 50)]

## dictionary comprehension and counters

In [32]:
countries = {'France': 5, 'Thailand': 0, 'Burkina Faso': 4,'Australia':8, 'Canada': 3, 'Venezuala': 7}
countries_sum= {k:v*2 for k, v in countries.items()}
countries_sum

{'Australia': 16,
 'Burkina Faso': 8,
 'Canada': 6,
 'France': 10,
 'Thailand': 0,
 'Venezuala': 14}

In [35]:
chant_names_countries = {k*3+'!':v for k, v in countries.items()}
chant_names_countries

{'AustraliaAustraliaAustralia!': 8,
 'Burkina FasoBurkina FasoBurkina Faso!': 4,
 'CanadaCanadaCanada!': 3,
 'FranceFranceFrance!': 5,
 'ThailandThailandThailand!': 0,
 'VenezualaVenezualaVenezuala!': 7}

In [30]:
stuff_to_count=['and','and','and','and','or','or','or','ought','ought','ought','ought','ought']
di = {}

for i in stuff_to_count:
  if i in di:
    di[i] += 1
  else:
    di[i] = 1  

print(di)

{'and': 4, 'or': 3, 'ought': 5}


## %timeit

In [36]:
%timeit chant_names_countries = {k*3+'!':v for k, v in countries.items()}
chant_names_countries

The slowest run took 6.24 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.58 µs per loop


{'AustraliaAustraliaAustralia!': 8,
 'Burkina FasoBurkina FasoBurkina Faso!': 4,
 'CanadaCanadaCanada!': 3,
 'FranceFranceFrance!': 5,
 'ThailandThailandThailand!': 0,
 'VenezualaVenezualaVenezuala!': 7}

In [39]:
%%timeit
def lists(list1, list2):
  enum_list = [(list1[item], match) for item, match in enumerate(list2)]
  return enum_list

lists(names, randtime)  

The slowest run took 6.88 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.02 µs per loop


In [41]:
def lists(list1, list2):
  enum_list = [(list1[item], match) for item, match in enumerate(list2)]
  return enum_list
lists(names, randtime)

[('Jerry', 0),
 ('Terry', 10),
 ('Gary', 20),
 ('Mary', 30),
 ('Larry', 40),
 ('Barry', 50)]

### set()

In [42]:
names = ['John', 'Anne','Phyllis','Derek','Janie', 'John', 'Ann', 'Anne']
names2 = ['Miranda','Fergus','Craig','Alison','Stephanie','Derek','Janie']

set_1 = set(names)
set_2 = set(names2)

set_1.intersection(set_2)

{'Derek', 'Janie'}

In [43]:
set_1.difference(set_2)

{'Ann', 'Anne', 'John', 'Phyllis'}

In [44]:
set_2.difference(set_1)

{'Alison', 'Craig', 'Fergus', 'Miranda', 'Stephanie'}

In [45]:
set_1.symmetric_difference(set_2)

{'Alison',
 'Ann',
 'Anne',
 'Craig',
 'Fergus',
 'John',
 'Miranda',
 'Phyllis',
 'Stephanie'}

In [46]:
set_1.union(set_2)

{'Alison',
 'Ann',
 'Anne',
 'Craig',
 'Derek',
 'Fergus',
 'Janie',
 'John',
 'Miranda',
 'Phyllis',
 'Stephanie'}

In [47]:
stuff_to_count=['and','and','and','and','or','or','or','ought','ought','ought','ought','ought']
setof = set(stuff_to_count)
setof

{'and', 'or', 'ought'}

## filter()

In [95]:
import statistics
nums = [1,2,3,4,5,7,6,7,8,9]
mean = statistics.mean(nums)
mode = statistics.mode(nums)
print(mean, mode)
print(list(filter(lambda x: x > mean, nums)))
print(list(filter(lambda x: x < mode, nums)))

5.2 7
[7, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6]


## reduce()
runs throug a list implementing a function on each item with output of previous item as input to current.

In [100]:
from functools import reduce
reduce(lambda x, y: x*y, nums), reduce(lambda x, y: x if x > y else y, nums)

(2540160, 9)

## generators

In [49]:
nums = [1,2,3,4,5,6,7,8,9,10]

def gen_x_squared(num_list):

    for num in num_list:
        yield num * num
        
gen_next_num = gen_x_squared(nums)
print(next(gen_next_num))
print(next(gen_next_num))
print(next(gen_next_num))
print(next(gen_next_num))
print(next(gen_next_num))

1
4
9
16
25


## memoization
way to use less memory when implementing recursive functions <br>
identify base case

In [56]:
# Original way that uses too much memory for high inputs
def fib(n):
  if n <=2:
    return 1
  else:
    return fib(n-1) + fib(n-2)

fib(100)

KeyboardInterrupt: ignored

In [61]:
nums = {}

def fibm(n):
  if n <=2:
    return 1
  if n in nums:
    return nums[n]
  else:
    num =  fibm(n-1) + fibm(n-2)
    nums[n] = num
    return num   

fibm(100), fibm(200), fibm(300), fibm(400), fibm(500), fibm(600),fibm(700), fibm(800), fibm(900), fibm(1000)     

(354224848179261915075,
 280571172992510140037611932413038677189525,
 222232244629420445529739893461909967206666939096499764990979600,
 176023680645013966468226945392411250770384383304492191886725992896575345044216019675,
 139423224561697880139724382870407283950070256587697307264108962948325571622863290691557658876222521294125,
 110433070572952242346432246767718285942590237357555606380008891875277701705731473925618404421867819924194229142447517901959200,
 87470814955752846203978413017571327342367240967697381074230432592527501911290377655628227150878427331693193369109193672330777527943718169105124275,
 69283081864224717136290077681328518273399124385204820718966040597691435587278383112277161967532530675374170857404743017623467220361778016172106855838975759985190398725,
 54877108839480000051413673948383714443800519309123592724494953427039811201064341234954387521525390615504949092187441218246679104731442473022013980160407007017175697317900483275246652938800,
 434665576869374564356885276750

### hash maps

In [72]:
first_hash = [None] * 15
print(first_hash)

def basic_hashing(key):
    return key % len(first_hash)

print(basic_hashing(15))    
print(basic_hashing(10))  
print(basic_hashing(18))     

[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
0
10
3


In [73]:
def insert(hash_table, key, value): # Does not account for collisions, previous data is overwritten
    hash_key = basic_hashing(key)
    hash_table[hash_key] = value 
insert(first_hash, 12, "frog") 
insert(first_hash, 15, "satchel" )
print(first_hash)
insert(first_hash, 15, "backbpack")
print(first_hash)

['satchel', None, None, None, None, None, None, None, None, None, None, None, 'frog', None, None]
['backbpack', None, None, None, None, None, None, None, None, None, None, None, 'frog', None, None]


In [80]:
#Use list of lists to prevent overwriting of data
third_hash = [[] for x in range(15)]
print(third_hash)

[[], [], [], [], [], [], [], [], [], [], [], [], [], [], []]


In [81]:
def better_hashing(hash_table, key):
    return key % len(hash_table)

print(better_hashing(third_hash, 18))   

3


In [83]:
def insert(hash_table, key, value):
    hash_key = better_hashing(hash_table, key)
    hash_table[hash_key].append(value)

insert(third_hash, 18, "elephant")
insert(third_hash,18, "giraffe")
insert(third_hash, 16, 'cat')
print(third_hash)  

[[], ['cat', 'cat'], [], ['elephant', 'giraffe', 'elephant', 'giraffe'], [], [], [], [], [], [], [], [], [], [], []]


In [89]:
# Creating a hash table of a list of lists of tuples
third_hash = [[] for x in range(15)]
def insert(hash_table, key, value):
    hash_key = hash(key) % len(hash_table)
    key_exists = False
    bucket = hash_table[hash_key]
    for kv in enumerate(bucket): 
        k,v = kv
        if key == k:
            key_exists = True
            break
    if key_exists:
        bucket[i] = ((key, value)) # where did 'i' come from?  why are we allowed to insert it there?
    else:
        bucket.append((key, value)) 

# Practice enumerate
x = enumerate(['ball','coin','cat'])
print(list(x))           

# Call latest hash function
insert(third_hash, 18, "chihuahua")
insert(third_hash, 18, "poodle")
insert(third_hash, 15, "doberman")
insert(third_hash, 15, "mastiff")
print(third_hash)




[(0, 'ball'), (1, 'coin'), (2, 'cat')]
[[(15, 'doberman'), (15, 'mastiff')], [], [], [(18, 'chihuahua'), (18, 'poodle')], [], [], [], [], [], [], [], [], [], [], []]


In [91]:
# Search hash table
def search(hash_table, key):
    hash_key = hash(key) % len(hash_table)
    bucket = hash_table[hash_key]
    for kv in enumerate(bucket):
        k, v = kv
        if key == k:
            return v

print(search(third_hash, 0))
 

(15, 'doberman')


In [93]:

# Deleting values 
def delete(hash_table, key):
    hash_key = hash(key) % len(hash_table)
    bucket = hash_table[hash_key]
    for kv in enumerate(bucket):
        k, v = kv
        if key == k:
            del hash_table[hash_key] 
    print(hash_table) 


delete(third_hash, 0)    

[[], [], [(18, 'chihuahua'), (18, 'poodle')], [], [], [], [], [], [], [], [], [], [], []]
